# TASK 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 120)

In [2]:
df = pd.read_csv('used_cars_messy.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

From the information we can see that the km_driven, mileage are in str format when they should be in int64 format this is mostly due to some rows having 'km' or 'kms' in the km_driven column and 'kmpl' in the mileage column

There are also some nulls in the selling price column we would need to drop all of those rows and we have alot of engine values missing we need to check whether to impute those or drop them as well same for mileage max power and seats

In [4]:
print(df.describe())

         Unnamed: 0   vehicle_age        engine     max_power         seats  selling_price
count  15661.000000  15661.000000  13792.000000  14862.000000  15218.000000   1.550300e+04
mean    9808.189643      6.036843   1480.489342    100.513582      5.324418   1.032764e+06
std     5642.981540      3.015072    511.446057     42.854632      0.805993   1.607380e+07
min        0.000000      0.000000    793.000000     38.400000      0.000000   5.000000e+02
25%     4901.000000      4.000000   1197.000000     74.000000      5.000000   3.850000e+05
50%     9858.000000      6.000000   1248.000000     88.500000      5.000000   5.550000e+05
75%    14666.000000      8.000000   1582.000000    117.300000      5.000000   8.250000e+05
max    19543.000000     29.000000   6592.000000    626.000000      9.000000   1.000000e+09

We can see that there is a row with 0 seats which isn't supposed to be possible and also the minimum vehicle age is given as 0 which doesn't make sense?!

## TASK 2

In [7]:
df = df.drop(columns=['Unnamed: 0'])
print(f"Shape after dropping Unnamed: 0: {df.shape}")

Shape after dropping Unnamed: 0: (15661, 13)

REMOVING ALL THE BLANK SPACES from

In [8]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [12]:
df['brand'] = df['brand'].str.strip()

In [13]:
df['brand'].head(10)

0     Renault
1      Maruti
2       Honda
3    Mahindra
4    Mahindra
5     Hyundai
6     Hyundai
7      Maruti
8        Ford
9      Maruti
Name: brand, dtype: str

In [14]:
print(df['brand'].value_counts().head(10))

brand
Maruti        5077
Hyundai       3025
Honda         1508
Mahindra      1031
Toyota         806
Ford           802
Volkswagen     634
Renault        550
BMW            443
Tata           435
Name: count, dtype: int64

NOW WE DO THE SAME FOR FUEL AND ALSO CHANGE THEM TO UPPERCASE.

In [15]:
df['fuel_type'] = df['fuel_type'].str.strip().str.title()

In [16]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7765
Diesel      7544
Cng          302
Lpg           46
Electric       4
Name: count, dtype: int64

In [17]:
df['seller_type'] = df['seller_type'].str.strip().str.title()

typo_map = {
    'Individul': 'Individual',
    'Individuall': 'Individual',
    'Delaer': 'Dealer',
    'Trustmark Delaer': 'Trustmark Dealer'
}
df['seller_type'] = df['seller_type'].replace(typo_map)

In [20]:
df['seller_type'].value_counts()

seller_type
Dealer              9694
Individual          5792
Trustmark Dealer     175
Name: count, dtype: int64

CONVERTING THE NUMERICAL GROUPS which are in STRING FORMAT to NUMERICAL FORMATS

In [21]:
df['km_driven'] = df['km_driven'].astype(str).str.replace(',', '')
df['km_driven'] = df['km_driven'].str.replace(r'\s*(kms|km)\s*', '')
df['km_driven'] = pd.to_numeric(df['km_driven'], errors='coerce')

In [23]:
df['km_driven'].describe()

count    1.549500e+04
mean     5.562932e+04
std      5.169452e+04
min      1.000000e+02
25%      3.000000e+04
50%      5.000000e+04
75%      7.000000e+04
max      3.800000e+06
Name: km_driven, dtype: float64

In [24]:
df['mileage'] = df['mileage'].astype(str).str.replace(r'\s*kmpl\s*', '')
df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')

In [25]:
df['mileage'].head(10)

0    19.87
1    33.54
2      NaN
3    15.40
4    16.00
5    20.36
6    18.50
7    20.51
8    24.40
9    19.30
Name: mileage, dtype: float64

In [27]:
df.describe()

        vehicle_age     km_driven       mileage        engine     max_power         seats  selling_price
count  15661.000000  1.549500e+04  14176.000000  13792.000000  14862.000000  15218.000000   1.550300e+04
mean       6.036843  5.562932e+04     19.698414   1480.489342    100.513582      5.324418   1.032764e+06
std        3.015072  5.169452e+04      4.174729    511.446057     42.854632      0.805993   1.607380e+07
min        0.000000  1.000000e+02      4.000000    793.000000     38.400000      0.000000   5.000000e+02
25%        4.000000  3.000000e+04     17.000000   1197.000000     74.000000      5.000000   3.850000e+05
50%        6.000000  5.000000e+04     19.670000   1248.000000     88.500000      5.000000   5.550000e+05
75%        8.000000  7.000000e+04     22.700000   1582.000000    117.300000      5.000000   8.250000e+05
max       29.000000  3.800000e+06     33.540000   6592.000000    626.000000      9.000000   1.000000e+09

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  str
 1   brand              15661 non-null  str
 2   model              15661 non-null  str
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15495 non-null  float64
 5   seller_type        15661 non-null  str
 6   fuel_type          15661 non-null  str
 7   transmission_type  15661 non-null  str
 8   mileage            14176 non-null  float64
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.6 MB

Dropping rows where Selling Price isn't mentioned

In [30]:
df = df.dropna(subset=['selling_price'])

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  str
 1   brand              15503 non-null  str
 2   model              15503 non-null  str
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15337 non-null  float64
 5   seller_type        15503 non-null  str
 6   fuel_type          15503 non-null  str
 7   transmission_type  15503 non-null  str
 8   mileage            14035 non-null  float64
 9   engine             13651 non-null  float64
 10  max_power          14712 non-null  float64
 11  seats              15065 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.7 MB

for col in ['engine', 'mileage', 'max_power']:

In [33]:
median_val = df['engine'].median()
df['engine'] = df['engine'].fillna(median_val)

In [34]:
median_val = df['max_power'].median()
df['max_power'] = df['max_power'].fillna(median_val)

In [35]:
median_val = df['mileage'].median()
df['mileage'] = df['mileage'].fillna(median_val)

In [37]:
median_val=df['km_driven'].median()
df['km_driven'] = df['km_driven'].fillna(median_val)

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  str
 1   brand              15503 non-null  str
 2   model              15503 non-null  str
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15503 non-null  float64
 5   seller_type        15503 non-null  str
 6   fuel_type          15503 non-null  str
 7   transmission_type  15503 non-null  str
 8   mileage            15503 non-null  float64
 9   engine             15503 non-null  float64
 10  max_power          15503 non-null  float64
 11  seats              15065 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.7 MB

Now all that is left is seats we need to impute it but instead of doing it with median we'll do it with mode

In [40]:
mode_val = df['seats'].mode()[0]
df['seats'] = df['seats'].fillna(mode_val)

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  str
 1   brand              15503 non-null  str
 2   model              15503 non-null  str
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15503 non-null  float64
 5   seller_type        15503 non-null  str
 6   fuel_type          15503 non-null  str
 7   transmission_type  15503 non-null  str
 8   mileage            15503 non-null  float64
 9   engine             15503 non-null  float64
 10  max_power          15503 non-null  float64
 11  seats              15503 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.7 MB

NOW OUR DATA IS ALL CLEAN AND HAS NO NULL VALUES

In [42]:
df.describe()

        vehicle_age     km_driven       mileage        engine     max_power         seats  selling_price
count  15503.000000  1.550300e+04  15503.000000  15503.000000  15503.000000  15503.000000   1.550300e+04
mean       6.037283  5.557159e+04     19.690352   1452.628975     99.911683      5.315165   1.032764e+06
std        3.015918  5.158628e+04      3.972926    485.949263     41.854442      0.796559   1.607380e+07
min        0.000000  1.000000e+02      4.000000    793.000000     38.400000      0.000000   5.000000e+02
25%        4.000000  3.000000e+04     17.100000   1197.000000     74.000000      5.000000   3.850000e+05
50%        6.000000  5.000000e+04     19.670000   1248.000000     88.500000      5.000000   5.550000e+05
75%        8.000000  7.000000e+04     22.320000   1498.000000    113.400000      5.000000   8.250000e+05
max       29.000000  3.800000e+06     33.540000   6592.000000    626.000000      9.000000   1.000000e+09

IN any nice car there are atleast 2 seats so we need to drop the rows where the seats are less than 0

In [48]:
df = df[df['seats'] >=2]

In [49]:
df.describe()

        vehicle_age     km_driven       mileage        engine     max_power         seats  selling_price
count  15494.000000  1.549400e+04  15494.000000  15494.000000  15494.000000  15494.000000   1.549400e+04
mean       6.036208  5.558928e+04     19.693947   1452.060475     99.832928      5.317349   1.031418e+06
std        3.014185  5.159495e+04      3.969925    485.151519     41.672218      0.791364   1.607828e+07
min        0.000000  1.000000e+02      4.000000    793.000000     38.400000      4.000000   5.000000e+02
25%        4.000000  3.000000e+04     17.100000   1197.000000     74.000000      5.000000   3.850000e+05
50%        6.000000  5.000000e+04     19.670000   1248.000000     88.500000      5.000000   5.550000e+05
75%        8.000000  7.000000e+04     22.320000   1498.000000    113.400000      5.000000   8.207500e+05
max       29.000000  3.800000e+06     33.540000   6592.000000    626.000000      9.000000   1.000000e+09

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 15494 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15494 non-null  str
 1   brand              15494 non-null  str
 2   model              15494 non-null  str
 3   vehicle_age        15494 non-null  int64
 4   km_driven          15494 non-null  float64
 5   seller_type        15494 non-null  str
 6   fuel_type          15494 non-null  str
 7   transmission_type  15494 non-null  str
 8   mileage            15494 non-null  float64
 9   engine             15494 non-null  float64
 10  max_power          15494 non-null  float64
 11  seats              15494 non-null  float64
 12  selling_price      15494 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.7 MB

## NOW WE NEED TO DO ENCODING

In [ ]:
df = pd.get_dummies(df, columns=['fuel_type', 'seller_type'], drop_first=True)

KeyError: "None of [Index(['fuel_type', 'seller_type'], dtype='str')] are in the [columns]"

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 15494 entries, 0 to 15660
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   car_name                      15494 non-null  str
 1   brand                         15494 non-null  str
 2   model                         15494 non-null  str
 3   vehicle_age                   15494 non-null  int64
 4   km_driven                     15494 non-null  float64
 5   transmission_type             15494 non-null  str
 6   mileage                       15494 non-null  float64
 7   engine                        15494 non-null  float64
 8   max_power                     15494 non-null  float64
 9   seats                         15494 non-null  float64
 10  selling_price                 15494 non-null  float64
 11  fuel_type_Diesel              15494 non-null  bool
 12  fuel_type_Electric            15494 non-null  bool
 13  fuel_type_Lpg                 15494 non-null  bool
 14  fuel_type_Petrol              15494 non-null  bool
 15  seller_type_Individual        15494 non-null  bool
 16  seller_type_Trustmark Dealer  15494 non-null  bool
dtypes: bool(6), float64(6), int64(1), str(4)
memory usage: 1.5 MB

In [54]:
df=df.drop(columns=['car_name'])

In [55]:
df.info()

<class 'pandas.DataFrame'>
Index: 15494 entries, 0 to 15660
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   brand                         15494 non-null  str
 1   model                         15494 non-null  str
 2   vehicle_age                   15494 non-null  int64
 3   km_driven                     15494 non-null  float64
 4   transmission_type             15494 non-null  str
 5   mileage                       15494 non-null  float64
 6   engine                        15494 non-null  float64
 7   max_power                     15494 non-null  float64
 8   seats                         15494 non-null  float64
 9   selling_price                 15494 non-null  float64
 10  fuel_type_Diesel              15494 non-null  bool
 11  fuel_type_Electric            15494 non-null  bool
 12  fuel_type_Lpg                 15494 non-null  bool
 13  fuel_type_Petrol              15494 non-null  bool
 14  seller_type_Individual        15494 non-null  bool
 15  seller_type_Trustmark Dealer  15494 non-null  bool
dtypes: bool(6), float64(6), int64(1), str(3)
memory usage: 1.4 MB

In [56]:
df.head()

,brand,model,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,seller_type_Individual,seller_type_Trustmark Dealer
0,Renault,Duster,7,67647.0,Manual,19.87,1461.0,83.80,5.0,575000.0,True,False,False,False,False,False
1,Maruti,Wagon R,3,52000.0,Manual,33.54,998.0,67.04,5.0,435000.0,False,False,False,False,False,False
2,Honda,City,3,48959.0,Manual,19.67,1497.0,117.60,5.0,875000.0,False,False,False,True,False,False
3,Mahindra,Scorpio,6,82000.0,Manual,15.40,2179.0,88.50,8.0,925000.0,True,False,False,False,False,False
4,Mahindra,XUV500,4,34000.0,Automatic,16.00,2179.0,140.00,7.0,1175000.0,True,False,False,False,False,False

In [60]:
df=pd.get_dummies(df,columns=['transmission_type'],drop_first=True)

In [62]:
df.info()

<class 'pandas.DataFrame'>
Index: 15494 entries, 0 to 15660
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   brand                         15494 non-null  str
 1   model                         15494 non-null  str
 2   vehicle_age                   15494 non-null  int64
 3   km_driven                     15494 non-null  float64
 4   mileage                       15494 non-null  float64
 5   engine                        15494 non-null  float64
 6   max_power                     15494 non-null  float64
 7   seats                         15494 non-null  float64
 8   selling_price                 15494 non-null  float64
 9   fuel_type_Diesel              15494 non-null  bool
 10  fuel_type_Electric            15494 non-null  bool
 11  fuel_type_Lpg                 15494 non-null  bool
 12  fuel_type_Petrol              15494 non-null  bool
 13  seller_type_Individual        15494 non-null  bool
 14  seller_type_Trustmark Dealer  15494 non-null  bool
 15  transmission_type_Manual      15494 non-null  bool
dtypes: bool(7), float64(6), int64(1), str(2)
memory usage: 1.3 MB

In [63]:
df.head()

,brand,model,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_type_Manual
0,Renault,Duster,7,67647.0,19.87,1461.0,83.80,5.0,575000.0,True,False,False,False,False,False,True
1,Maruti,Wagon R,3,52000.0,33.54,998.0,67.04,5.0,435000.0,False,False,False,False,False,False,True
2,Honda,City,3,48959.0,19.67,1497.0,117.60,5.0,875000.0,False,False,False,True,False,False,True
3,Mahindra,Scorpio,6,82000.0,15.40,2179.0,88.50,8.0,925000.0,True,False,False,False,False,False,True
4,Mahindra,XUV500,4,34000.0,16.00,2179.0,140.00,7.0,1175000.0,True,False,False,False,False,False,False

It would've been better to do binary classification to the transmission type but for now we will just leave it as it is

## NOW WE CAN TRAIN THE DATA

In [64]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

Calculating the mean selling price from the training set

In [72]:
baseline_prediction = y_train.mean()

print("Mean Selling Price:",baseline_prediction)

Mean Selling Price: 1018692.5269866881

In [73]:
y_pred_baseline = np.full(len(y_test), baseline_prediction)

In [74]:
from sklearn.metrics import mean_absolute_error

In [75]:
baseline_mae = mean_absolute_error(y_test, y_pred_baseline)

print("Baseline MAE:",baseline_mae)

Baseline MAE: 895751.5562856294